// brew.go — the Homebrew channel: render a formula and commit it into the
// shared tap.
//
// Credential-gated like every channel (spec, "Distribution channels"):
// no tap configured → not attempted; tap configured but no way to push →
// loud skip, never a failed release. The push happens through `gh api` so
// the user's existing gh auth is the credential — no extra token plumbing
// for same-account taps.
package publish

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
	"text/template"
)

// BrewConfig is the `brew:` block of .volt.yml.
type BrewConfig struct {
	Tap         string `yaml:"tap"`         // "owner/homebrew-name" — empty disables the channel
	Description string `yaml:"description"` // formula desc; falls back to the repo description
	License     string `yaml:"license"`
}

// formulaTmpl is a minimal binary-install formula: one bottle-less formula
// per CLI, downloading the released archives. Kept deliberately simple —
// anything fancier (heads, services) belongs in a hand-written formula.
const formulaTmpl = `# Code generated by volt — DO NOT EDIT.
# Regenerate by releasing {{.Binary}}; edits here are overwritten on the next release.
class {{.ClassName}} < Formula
  desc "{{.Desc}}"
  homepage "https://github.com/{{.Repo}}"
  version "{{.BareVersion}}"
  license "{{.License}}"

  on_macos do
    on_arm do
      url "{{.URL "darwin" "arm64"}}"
      sha256 "{{.SHA "darwin" "arm64"}}"
    end
    on_intel do
      url "{{.URL "darwin" "amd64"}}"
      sha256 "{{.SHA "darwin" "amd64"}}"
    end
  end
  on_linux do
    on_arm do
      url "{{.URL "linux" "arm64"}}"
      sha256 "{{.SHA "linux" "arm64"}}"
    end
    on_intel do
      url "{{.URL "linux" "amd64"}}"
      sha256 "{{.SHA "linux" "amd64"}}"
    end
  end

  def install
    bin.install "{{.Binary}}"
  end

  test do
    system "#{bin}/{{.Binary}}", "--version"
  end
end
`

// FormulaData feeds the template. Sums maps "os/arch" → sha256 hex; a
// platform absent from the release is absent here, and the template method
// yields "" (brew then fails loudly on install for that platform — honest).
type FormulaData struct {
	Binary      string
	ClassName   string
	Desc        string
	Repo        string
	Tag         string
	BareVersion string
	License     string
	Sums        map[string]string
}

// URL builds the release-asset URL for one platform.
func (d FormulaData) URL(osName, arch string) string {
	return fmt.Sprintf("https://github.com/%s/releases/download/%s/%s_v%s_%s_%s.tar.gz",
		d.Repo, d.Tag, d.Binary, d.BareVersion, osName, arch)
}

// SHA returns the recorded checksum for one platform.
func (d FormulaData) SHA(osName, arch string) string { return d.Sums[osName+"/"+arch] }

// RenderFormula produces the formula text.
func RenderFormula(d FormulaData) (string, error) {
	if d.ClassName == "" {
		d.ClassName = classNameFor(d.Binary)
	}
	if d.License == "" {
		d.License = "NOASSERTION"
	}
	t, err := template.New("formula").Parse(formulaTmpl)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	if err := t.Execute(&b, d); err != nil {
		return "", err
	}
	return b.String(), nil
}

// classNameFor converts a binary name to a Ruby class name the way brew
// expects: "my-cli" → "MyCli".
func classNameFor(binary string) string {
	var b strings.Builder
	up := true
	for _, r := range binary {
		switch {
		case r == '-' || r == '_':
			up = true
		case up:
			b.WriteString(strings.ToUpper(string(r)))
			up = false
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// SumsFromChecksums parses a checksums.txt into the "os/arch"→sha map the
// formula needs, matching only this binary's tar.gz assets.
func SumsFromChecksums(path, binary string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()
	raw, err := io.ReadAll(f)
	if err != nil {
		return nil, err
	}
	sums := map[string]string{}
	for _, line := range strings.Split(string(raw), "\n") {
		fields := strings.Fields(line)
		if len(fields) != 2 || !strings.HasPrefix(fields[1], binary+"_") || !strings.HasSuffix(fields[1], ".tar.gz") {
			continue
		}
		// <binary>_<version>_<os>_<arch>.tar.gz
		parts := strings.Split(strings.TrimSuffix(fields[1], ".tar.gz"), "_")
		if len(parts) < 4 {
			continue
		}
		sums[parts[len(parts)-2]+"/"+parts[len(parts)-1]] = fields[0]
	}
	return sums, nil
}

// PushFormula commits the formula into the tap repo via the GitHub contents
// API (gh api) — create or update, using the caller's gh auth. Same-account
// taps need no extra token; a cross-account tap failure surfaces as the
// returned error, which the release reports as a skipped channel.
func PushFormula(tap, binary, formula, message string) error {
	path := fmt.Sprintf("Formula/%s.rb", binary)
	body := map[string]string{
		"message": message,
		"content": base64.StdEncoding.EncodeToString([]byte(formula)),
	}
	// Existing file? Its sha is required for an update.
	if out, err := ghAPI("GET", fmt.Sprintf("repos/%s/contents/%s", tap, path), nil); err == nil {
		var cur struct {
			SHA string `json:"sha"`
		}
		if json.Unmarshal(out, &cur) == nil && cur.SHA != "" {
			body["sha"] = cur.SHA
		}
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return err
	}
	_, err = ghAPI("PUT", fmt.Sprintf("repos/%s/contents/%s", tap, path), payload)
	return err
}

func ghAPI(method, path string, body []byte) ([]byte, error) {
	args := []string{"api", "-X", method, path}
	var stdin io.Reader
	if body != nil {
		args = append(args, "--input", "-")
		stdin = bytes.NewReader(body)
	}
	cmd := exec.Command("gh", args...)
	cmd.Stdin = stdin
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("gh api %s %s: %s", method, path, strings.TrimSpace(errb.String()))
	}
	return out.Bytes(), nil
}

// FormulaSHA256 is exposed for tests: the hash brew will verify.
func FormulaSHA256(b []byte) string { return fmt.Sprintf("%x", sha256.Sum256(b)) }
