// Package appmeta carries the identity of the binary built from this template:
// its name, env-var prefix, on-disk directory names, and where its SQLite file
// lives.
//
// WHY this exists as data instead of scattered string literals: every one of
// these values appears in a dozen places (help text, env lookup, path
// resolution, error hints, the installer, the brew formula). Centralizing them
// means scaffolding a new project rewrites ONE file, and every library package
// under modules/core can stay app-agnostic by taking a Meta as a parameter
// rather than importing a hardcoded name.
//
// INVARIANT: nothing in modules/core may hardcode an app name. If a package
// needs one, it accepts a Meta.
//
// Roadmap: this file is hand-written today. Once volt.yaml exists it becomes
// appmeta.gen.go, generated by `task gen` with a CI drift check. The exported
// surface is designed to survive that switch unchanged.
package appmeta

// DBLocation selects the policy used to resolve the SQLite file path.
//
// It is a POLICY, never a baked absolute path: the build machine's $HOME is not
// the user's, and a literal "~" in a path creates a directory named "~".
// Resolution happens at runtime from this policy — see modules/core/appdir.
type DBLocation string

const (
	// LocationUserGlobal puts one database per user under the OS config dir
	// (os.UserConfigDir()/<Name>/<DBFilename>). Use for tools whose state is
	// about the user, not about a checkout.
	LocationUserGlobal DBLocation = "user-global"

	// LocationProjectLocal walks up from the working directory looking for
	// <DirName>/, the way git finds .git. Use for tools whose state belongs to
	// a repository.
	LocationProjectLocal DBLocation = "project-local"

	// LocationBoth resolves project-local first and falls back to user-global.
	// Use when a tool has both per-repo and machine-wide state.
	LocationBoth DBLocation = "both"
)

// Valid reports whether l is a known policy. Guards against a hand-edited or
// mis-generated value silently falling through to a default at runtime.
func (l DBLocation) Valid() bool {
	switch l {
	case LocationUserGlobal, LocationProjectLocal, LocationBoth:
		return true
	}
	return false
}

// Meta is the full identity of one binary. Library packages accept this rather
// than reaching for package-level constants, which is what makes them reusable
// across every app scaffolded from this template.
type Meta struct {
	// Name is the product name used in help text and directory paths.
	Name string

	// Binary is the executable name as it appears on PATH. Usually equal to
	// Name, but kept separate because they legitimately diverge (product
	// "Volt CLI", binary "volt").
	Binary string

	// EnvPrefix prefixes every environment variable the app reads, e.g. "VOLT"
	// yields VOLT_DB, VOLT_READ_ONLY, VOLT_TRACE.
	EnvPrefix string

	// DirName is the per-project state directory searched for by
	// LocationProjectLocal. Conventionally dot-prefixed.
	DirName string

	// DBFilename is the SQLite filename inside the resolved directory.
	DBFilename string

	// DBLocation is the path-resolution policy. See DBLocation.
	DBLocation DBLocation

	// DocsURL is the base for error documentation links; error codes are
	// appended to it to build a per-code deep link.
	DocsURL string
}

// Default is this template's own identity. Scaffolding a new project replaces
// this block (and nothing else in modules/core).
var Default = Meta{
	Name:       "demo",
	Binary:     "demo",
	EnvPrefix:  "DEMO",
	DirName:    ".demo",
	DBFilename: "demo.db",
	DBLocation: LocationProjectLocal,
	DocsURL:    "https://github.com/khanakia/voltkit/blob/main/docs/errors",
}
